---
title: There are 4 types of people...
author: Bruce Meng
date: '2018-01-05'
slug: there-are-4-types-of-people
categories: []
tags: []
---

I was talking recently with my friend [`@k_trinhy`](https://twitter.com/k_trinhy) and I was relaying to her a profound categorization of people by a German Army general:

> I divide my officers into four groups. There are clever, diligent, stupid, and lazy officers. <br><br>
Usually two characteristics are combined. <br><br>
Some are clever and diligent -- their place is the General Staff. <br><br>
The next lot are stupid and lazy -- they make up 90 percent of every army and are suited to routine duties. <br><br>
Anyone who is both clever and lazy is qualified for the highest leadership duties, because he possesses the intellectual clarity and the composure necessary for difficult decisions. <br><br>
One must beware of anyone who is stupid and diligent -- he must not be entrusted with any responsibility because he will always cause only mischief. <br><br>
-- *Kurt von Hammerstein-Equord*


[Wikipedia source](https://en.wikiquote.org/wiki/Kurt_von_Hammerstein-Equord)

This was the best system of categorizing people I have so far seen. `r emo::ji("smile")`