---
title: Check out SN2-D2 (a friendly lil sentiment droid)!
author: Bruce Meng
date: '2018-04-05'
slug: check-out-sn2-d2
categories: []
tags:
  - fun
  - cool
  - bot
---

I've been reading reddit for a while now, and I've noticed that reddit has a lot of really funny and really useful bots!

The most impressive bot that I've encountered is **[AutoTLDR](https://www.reddit.com/r/autotldr/comments/31b9fm/faq_autotldr_bot/)**. It will automatically reduce long articles by at least 70% and I found that the quality of the summaries it creates is often times indistinguishable from a human summary.

AutoTLDR inspired me to try to create something that resembles a bot too... and so SN2-D2 is born in the Projects section! (In case you missed it... SN2-D2 is my very subtle play on the most famous droid of all time: R2-D2).

# SN2-D2 Droid

SN2-D2 was created so I (and you) can interactively access a specific custom trained sentiment analysis algorithm I created at work to read and assess a particular business report that quite a few people at BMO read. 

I'm not sure how well it will assess all Internet sentences since it was trained to specifically read one type of report, but my volunteer testers and I have been having fun subjecting it to all sorts of weird and wacky sentences `r emo::ji("smile")`.

Please feel free to try out **[SN2-D2](../../project/sn2-d2/)** yourself and let me know of how well (or not well!) it works for you!