---
title: Animations in R
author: Bruce Meng
date: '2018-03-18'
slug: animations-in-r
categories: []
tags:
  - R
---

```{r setup, include=F}
library(tidyverse)
library(plotly)

```

When I was in school, I always found that the blackboard was the best teaching tool (as opposed to say a pre-prepared static slide in PowerPoint). As a student, I found it really helpful to see a concept get built up from nothing, and accordingly when I was a teaching assistant in economics, I also preferred using the blackboard to build up concepts together with my students (I also found it more fun as it was now a collaborative experience). Now in the business world, developing concepts is still as important as when I was in school, and the closest computer-presentation equivalent to the blackboard is... the animation!

I've been trying two methods with animations:

1. `gganimate` & `tweenr`
2. `plotly`

Let's build a quick demo of each!

# `gganimate` with `tweenr`

First up, is a solution that's fully self-contained within the ggplot2 universe: the package `gganimate`.



